[package]
name = "mmo"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.11"
wgpu = "26.0.1"
log = "0.4"
env_logger = "0.11"
pollster = "0.3" 
bytemuck = { version = "1.15", features = ["derive"] }
glam = { version = "0.27", features = ["bytemuck"] }